kafka: 
  bootstrap-servers: localhost:9092

  topic:
    spring-integration-kafka: integration-topic
logging:
  level:
    root: off
    '[com.farhad.example]': info
spring: 
  main: 
    allow-circular-references: true